### ISSUE TITLE
[React 19] TypeError: u(...).findDOMNode is not a function when navigating between the months.

### ISSUE THREAD

**Issue by chaitanyareddy-mula** [edwardfhsiao/react-minimal-datetime-range#11]
Hi,
We are facing TypeError: u(...).findDOMNode is not a function error after updating our project from React 18 to 19 version. Since React 19, the findDOMNode function has been completely removed from the React and ReactDOM packages, your dependency package react-transition-group has fixed it in 4.4.0 version [Link](https://github.com/reactjs/react-transition-group/pull/559) and now its time to react-minimal-datetime-range to do the necessary changes as part of react-transition-group 4.4.0 in your code base to support React 19.

<img width="672" height="156" alt="Image" src="https://github.com/user-attachments/assets/0557df6f-87c5-4254-946a-cd1999b1eb93" />

**Comment by chaitanyareddy-mula** [comment]
Hi @edwardfxiao, Did you get a chance to look into the above issue?

**Comment by edwardfxiao** [comment]
Checkout v3.0.0

I was rushing to fix it because I don't have much time, so there are a lot of 'any'. Test it see it will work or not.

**Comment by chaitanyareddy-mula** [comment]
Hi @edwardfxiao, when i am trying to update to latest in my enterprise project, I am facing below issue.

Below is the screenshot of npm outdated:-

<img width="889" height="19" alt="Image" src="https://github.com/user-attachments/assets/53805a45-d94e-4926-bc8c-b34158b6f366" />

<img width="827" height="125" alt="Image" src="https://github.com/user-attachments/assets/589b1acd-e7c6-47fe-8283-34f4080a0a82" />

**Comment by edwardfxiao** [comment]
@chaitanyareddy-mula I am not sure what that means. But I have succesfully install here https://codesandbox.io/p/sandbox/index-z90y9?file=%2Fpackage.json%3A6%2C26

**Comment by chaitanyareddy-mula** [comment]
Hey @edwardfxiao, I am also trying to run npm i by taking pull from react-minimal-datetime-range master branch in order to test the example file and it is throwing below error. please find the log in attached image.

<img width="672" height="359" alt="Image" src="https://github.com/user-attachments/assets/7995f4ee-3f0a-4130-a7ad-7724d3591456" />

**Comment by edwardfxiao** [comment]
Have you done rm -rf node_modules/ and reinstall?

**Comment by chaitanyareddy-mula** [comment]
@edwardfxiao yes i removed the node_modules and trying reinstall. Please find below screenshot

<img width="1007" height="430" alt="Image" src="https://github.com/user-attachments/assets/de042a27-fbff-4549-a1ce-93a0207663d2" />

**Comment by chaitanyareddy-mula** [comment]
> Hi [@edwardfxiao](https://github.com/edwardfxiao), when i am trying to update to latest in my enterprise project, I am facing below issue.
> 
> Below is the screenshot of npm outdated:-
> 
> <img alt="Image" width="889" height="19" src="https://private-user-images.githubusercontent.com/64189047/547663881-53805a45-d94e-4926-bc8c-b34158b6f366.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA3MjQxNjYsIm5iZiI6MTc3MDcyMzg2NiwicGF0aCI6Ii82NDE4OTA0Ny81NDc2NjM4ODEtNTM4MDVhNDUtZDk0ZS00OTI2LWJjOGMtYjM0MTU4YjZmMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjEwVDExNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYjAwMTdlYjJhNmI1ZmVjZGVmZTg1Njk4ZDg1MWU2OTI2MzM1NDk2ZTMwYjE4NDg1YTE2ZDg5ODAyMTRkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LQxRBCEtQg-S1F54Y4GNmCLDPqGC_faKY8XnD-c9paY"> <img alt="Image" width="827" height="125" src="https://private-user-images.githubusercontent.com/64189047/547664629-589b1acd-e7c6-47fe-8283-34f4080a0a82.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA3MjQxNjYsIm5iZiI6MTc3MDcyMzg2NiwicGF0aCI6Ii82NDE4OTA0Ny81NDc2NjQ2MjktNTg5YjFhY2QtZTdjNi00N2ZlLTgyODMtMzRmNDA4MGEwYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjEwVDExNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTlhN2UyNTRhODQxMjhkYjU0YmNkZDg5MmMyNDk1MGIwNDYzMjQ5NDAwM2MxOTgwNTZmMTdjNzMxYjhmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IJA3PFUS-mfnrfV2ookqTo9twxD5DFQz1ki75yYDq04">

Sorry for this. Now i am able to install. Let me test my enterprise project. @edwardfxiao .

**Comment by edwardfxiao** [comment]
I removed it in 3.0.1, try again?

**Comment by chaitanyareddy-mula** [comment]
@edwardfxiao After taking pull and running the following commands  "rm -rf node_modules" and "npm i" i see below error

<img width="794" height="377" alt="Image" src="https://github.com/user-attachments/assets/06b94f2a-7bef-4b53-b8d5-d6e5cd67a0e5" />

**Comment by chaitanyareddy-mula** [comment]
I checked out to new branch in local (i.e: 13.0.2) and after upgrading the below packages to latest i can perform npm install successfully in local env.
npm install --save-dev jest@latest babel-jest@latest ts-jest@latest

**Comment by edwardfxiao** [comment]
@chaitanyareddy-mula can you create a very basic repository that share the same issue so I can take a look?

**Comment by edwardfxiao** [comment]
@chaitanyareddy-mula Also I rm all jest related and pushed 3.0.2, not sure if there are any other isues

**Comment by chaitanyareddy-mula** [comment]
Hi @edwardfxiao , I guess it is working now in my enterprise application after updating the version in package.json. 

However when i run the below commands in local master branch of your repo, I am facing below issue

<img width="1277" height="761" alt="Image" src="https://github.com/user-attachments/assets/4bfd37dc-9afa-4762-9ac9-c1d9049c16cd" />

**Comment by chaitanyareddy-mula** [comment]
> [@chaitanyareddy-mula](https://github.com/chaitanyareddy-mula) Also I rm all jest related and pushed 3.0.2, not sure if there are any other isues

Anyhow for my enterprise application the issue is unblocked now and it is working as expected. The above mention is when i try to run commands in your repository.

**Comment by edwardfxiao** [comment]
@chaitanyareddy-mula Maybe it is because I forgot to push to the repository.

**Comment by chaitanyareddy-mula** [comment]
@edwardfxiao  yeah now npm install is working as expected in your repository. I had test the following scripts and few are working as expected and few are throwing error. you can check it out later as build, dev script is working fine as expected.

Failed Scripts :- umd_local, umd_global, umd_global_min, compile

**Comment by chaitanyareddy-mula** [comment]
Closing this issue as version 3.0.2 has resolved it.
